# -*- encoding: utf-8 -*-
require "rails"
require "active_support"
require "active_record"
require "action_controller"
require "find_cache/version"
require "find_cache/init"
require "find_cache/key_gen"
require "find_cache/counter_cache"
require "find_cache/cacheable"
require "find_cache/controller_garbage_collector"
